//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal loc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.loc", typeof(loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountEN {
            get {
                return ResourceManager.GetString("AmountEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        internal static string AmountRU {
            get {
                return ResourceManager.GetString("AmountRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background settings.
        /// </summary>
        internal static string BackgroundSettingsEN {
            get {
                return ResourceManager.GetString("BackgroundSettingsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки заднего фона.
        /// </summary>
        internal static string BackgroundSettingsRU {
            get {
                return ResourceManager.GetString("BackgroundSettingsRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string CalculateEN {
            get {
                return ResourceManager.GetString("CalculateEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вычислить.
        /// </summary>
        internal static string CalculateRU {
            get {
                return ResourceManager.GetString("CalculateRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the background color.
        /// </summary>
        internal static string ChangeColorEN {
            get {
                return ResourceManager.GetString("ChangeColorEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поменять цвет заднего фона.
        /// </summary>
        internal static string ChangeColorRU {
            get {
                return ResourceManager.GetString("ChangeColorRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coca-Cola.
        /// </summary>
        internal static string CocaColaEN {
            get {
                return ResourceManager.GetString("CocaColaEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кола.
        /// </summary>
        internal static string CocaColaRU {
            get {
                return ResourceManager.GetString("CocaColaRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the week.
        /// </summary>
        internal static string DayOfTheWeekEN {
            get {
                return ResourceManager.GetString("DayOfTheWeekEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День недели.
        /// </summary>
        internal static string DayOfTheWeekRU {
            get {
                return ResourceManager.GetString("DayOfTheWeekRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French fries.
        /// </summary>
        internal static string FrenchFriesEN {
            get {
                return ResourceManager.GetString("FrenchFriesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картофель-фри.
        /// </summary>
        internal static string FrenchFriesRU {
            get {
                return ResourceManager.GetString("FrenchFriesRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        internal static string GasEN {
            get {
                return ResourceManager.GetString("GasEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топливо.
        /// </summary>
        internal static string GasRU {
            get {
                return ResourceManager.GetString("GasRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamburger.
        /// </summary>
        internal static string HamburgerEN {
            get {
                return ResourceManager.GetString("HamburgerEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бургер.
        /// </summary>
        internal static string HamburgerRU {
            get {
                return ResourceManager.GetString("HamburgerRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot-dog.
        /// </summary>
        internal static string HotDogEN {
            get {
                return ResourceManager.GetString("HotDogEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хот-дог.
        /// </summary>
        internal static string HotDogRU {
            get {
                return ResourceManager.GetString("HotDogRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language settings.
        /// </summary>
        internal static string LanguageSettingsEN {
            get {
                return ResourceManager.GetString("LanguageSettingsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Языковые настройки.
        /// </summary>
        internal static string LanguageSettingsRU {
            get {
                return ResourceManager.GetString("LanguageSettingsRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini-cafe.
        /// </summary>
        internal static string MiniCafeEN {
            get {
                return ResourceManager.GetString("MiniCafeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мини-кафе.
        /// </summary>
        internal static string MiniCafeRU {
            get {
                return ResourceManager.GetString("MiniCafeRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money.
        /// </summary>
        internal static string MoneyEN {
            get {
                return ResourceManager.GetString("MoneyEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string MoneyRU {
            get {
                return ResourceManager.GetString("MoneyRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil type.
        /// </summary>
        internal static string OilTypeEN {
            get {
                return ResourceManager.GetString("OilTypeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип топлива.
        /// </summary>
        internal static string OilTypeRU {
            get {
                return ResourceManager.GetString("OilTypeRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceEN {
            get {
                return ResourceManager.GetString("PriceEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        internal static string PriceRU {
            get {
                return ResourceManager.GetString("PriceRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string Switch1EN {
            get {
                return ResourceManager.GetString("Switch1EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключение.
        /// </summary>
        internal static string Switch1RU {
            get {
                return ResourceManager.GetString("Switch1RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to the next customer?.
        /// </summary>
        internal static string Switch2EN {
            get {
                return ResourceManager.GetString("Switch2EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключиться на следующего покупателя?.
        /// </summary>
        internal static string Switch2RU {
            get {
                return ResourceManager.GetString("Switch2RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pay.
        /// </summary>
        internal static string ToPayEN {
            get {
                return ResourceManager.GetString("ToPayEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К оплате.
        /// </summary>
        internal static string ToPayRU {
            get {
                return ResourceManager.GetString("ToPayRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total to pay.
        /// </summary>
        internal static string ToPayTotalEN {
            get {
                return ResourceManager.GetString("ToPayTotalEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего к оплате.
        /// </summary>
        internal static string ToPayTotalRU {
            get {
                return ResourceManager.GetString("ToPayTotalRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total daily income.
        /// </summary>
        internal static string TotalDailyIncomeEN {
            get {
                return ResourceManager.GetString("TotalDailyIncomeEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий доход за день.
        /// </summary>
        internal static string TotalDailyIncomeRU {
            get {
                return ResourceManager.GetString("TotalDailyIncomeRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total today.
        /// </summary>
        internal static string TotalDayEN {
            get {
                return ResourceManager.GetString("TotalDayEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего за день.
        /// </summary>
        internal static string TotalDayRU {
            get {
                return ResourceManager.GetString("TotalDayRU", resourceCulture);
            }
        }
    }
}
